import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { syllable } from "syllable";
import { useState } from "react";
export default function Home() {
  const [words, setWords] = useState([]);
  const [syllables, setSyllables] = useState([]);
  const [text, setText] = useState("");

  // create a function that pushes the text into the words array
  const handleClick = (e) => {
    e.preventDefault();
    setText(e.target.value);
    words.push(text);
    syllables.push(syllable(text));
    setSyllables([...syllables], syllable(text));
    setWords([...words], { text, syllables: syllable(text) });
  };
  console.log(words, "words");
  console.log(syllables, "syllables");
  // creat a function that returns the total number of syllables
  const totalSyllables = syllables.reduce((acc, curr) => {
    return acc + curr;
  }, 0);
  // create a function that returns the words once they have reached 5 syllables
  const wordsWithOneSyllable = words.filter((word) => syllable(word) === 1);
  const wordsWithTwoSyllables = words.filter((word) => syllable(word) === 2);
  const wordsWithThreeSyllables = words.filter((word) => syllable(word) === 3);
  const wordsWithFourSyllables = words.filter((word) => syllable(word) === 4);
  const wordsWithFiveSyllables = words.filter((word) => syllable(word) >= 5);
  const wordsWithSixSyllables = words.filter((word) => syllable(word) === 6);
  const wordsWithSevenSyllables = words.filter((word) => syllable(word) === 7);
  console.log(wordsWithOneSyllable, "wordsWithOneSyllable");
  console.log(wordsWithTwoSyllables, "wordsWithTwoSyllables");
  console.log(wordsWithThreeSyllables, "wordsWithThreeSyllables");
  console.log(wordsWithFourSyllables, "wordsWithFourSyllables");
  console.log(wordsWithFiveSyllables, "wordsWithFiveSyllables");
  console.log(totalSyllables, "total syllables");
  // create a function that combines the words to add up to 5 syllable count
  const totalSyllableCount = words.reduce((acc, curr) => {
    return acc + syllable(curr);
  }
  , 0);
  const combineWords = words.reduce((acc, curr) => {
    return acc + curr;
  }
  , "");
  let combinedWords = [];
  if (totalSyllableCount === 5) {
    combinedWords.push(combineWords);
    console.log("WE MADE IT TO 5 SYLLABLES");
  }
  if (totalSyllableCount === 6) {
    alert("Oops you need 5 syllables");
  }
  console.log(combineWords, "combineWords");
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1>Haiku gg</h1>
        <form>
          <input
            type="text"
            value={text}
            onChange={(e) => setText(e.target.value)}
          />
          <button onClick={handleClick}>Submit</button>
          {words.map((word, index) => {
            return (
              <div key={index}>
                <p>
                  {word} + {syllable(word)}
                </p>
              </div>
            );
          })}
        </form>
      </main>

      <footer className={styles.footer}>
        <p>Copyright © 2022</p>
      </footer>
    </div>
  );
}
